# Generated by Django 5.2.7 on 2025-10-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videogeneration",
            name="image_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="videogeneration",
            name="image_s3_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="videogeneration",
            name="original_image_base64",
            field=models.TextField(blank=True, null=True),
        ),
    ]
