# Generated by Django 5.2.7 on 2025-10-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_videogeneration_image_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videogeneration",
            name="voice_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="videogeneration",
            name="voice_provider",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
