# Generated by Django 5.2.7 on 2025-10-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videogeneration",
            name="original_image_base64",
        ),
    ]
