# Generated by Django 5.2.7 on 2025-11-09 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_passwordresetotp_alter_videogeneration_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="videogeneration",
            name="avatar_scale",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="videogeneration",
            name="avatar_shape",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="videogeneration",
            name="avatar_x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="videogeneration",
            name="avatar_y",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="videogeneration",
            name="background_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="videogeneration",
            name="background_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="videogeneration",
            name="input_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="videogeneration",
            name="need_subtitles",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="videogeneration",
            name="platform",
            field=models.CharField(default="d-id", max_length=20),
        ),
        migrations.AddField(
            model_name="videogeneration",
            name="talking_photo_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="videogeneration",
            name="talking_photo_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="videogeneration",
            name="voice_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="videogeneration",
            name="script_input",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="videoview",
            unique_together={("user", "video")},
        ),
    ]
